name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  pmtiles:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{github.event.pull_request.head.sha || github.sha}}

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Install
        working-directory: ./tasks/pmtiles/
        run: npm install

      - name: Lint
        working-directory: ./tasks/pmtiles/
        run: npm run lint

      - name: Check
        working-directory: ./tasks/pmtiles/
        run: npm run check

      - name: Build
        working-directory: ./tasks/pmtiles/
        run: npm run build
